[package]
name = "zerone"
version = "0.1.0"
authors = ["Ramon Moraes"]
edition = "2018"

[profile.release]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
